### ISSUE TITLE
md5deep ignores file order

### ISSUE THREAD

**Issue by ghost** [jessek/hashdeep#316]
md5deep ignores the order of file lists supplied either as an argument or read from a file.

For example, the on-disk ordering is: C, A, B.

Let's say we have a file mylist.txt with the following contents:
./A
./B
./C

Running 'md5deep -rlz -f mylist.txt' produces the output in the on-disk order: C, A, B instead of the order specified in the arguments file: A, B, C.

The same for the files specified on the command line: running 'md5deep A B C' will report C A B.

Version: 4.4

**Comment by lezsakdomi** [comment]
The documentation says to use `-j0` for deterministic output. Neither works for me.
Here is the demonstration:
https://github.com/lezsakdomi/elte-mester-data/commit/576533c59d114aa341b3682c1c99877ffba319f9
Please see the chain of parent commits.
