### ISSUE TITLE
Whirlpool hash incorrect

### ISSUE THREAD

**Issue by dimavs** [jessek/hashdeep#327]
Just downloaded and installed 4.4 release.

$ echo "" | whirlpooldeep
898126aab982feb2e4b99fee1e4b1cfb4208c76f35945119d24de8744016b56666dabeed478e3a9a36032bc9b8da05db7e79156dc76a7447ad0d39067745de1e
$ echo "The quick brown fox jumps over the lazy dog" | whirlpooldeep
72687676756b91ad986f2e56df761b354b748bc20098354b017b924e82cc67ae059da85f009d1a17c0f12ec0e644c0c3a193f3fc0fee22f053edbfcd95cbf873

According to wikipedia
 Whirlpool("") =
 19FA61D75522A4669B44E39C1D2E1726C530232130D407F89AFEE0964997F7A7
 3E83BE698B288FEBCF88E3E03C4F0757EA8964E59B63D93708B138CC42A66EB3
Whirlpool("The quick brown fox jumps over the lazy dog") =
 B97DE512E91E3828B40D2B0FDCE9CEB3C4A71F9BEA8D88E75C4FA854DF36725F
 D2B52EB6544EDCACD6F8BEDDFEA403CB55AE31F03AD62A5EF54E42EE82C3FB35

What I am doing wrong?

**Comment by simsong** [comment]
Try `echo -n` --- you are including a newline in your output.

**Comment by dimavs** [comment]
Thanks! I forgot about it
