### ISSUE TITLE
OSX - Can't compile with XCode Command Line Tools installed

### ISSUE THREAD

**Issue by jjarava** [jessek/hashdeep#335]
Hi!

I'm trying to get the project to build in OSX
I'm using 10.9:

```
jjarava$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.9.5
BuildVersion:   13F1077
```

I have the Command Line tools from XCode installed, but the bootstrap.sh complains:

```
jjarava$ sh bootstrap.sh
bootstrap.sh: line 2: autoheader: command not found
bootstrap.sh: line 5: aclocal: command not found
bootstrap.sh: line 6: autoconf: command not found
bootstrap.sh: line 7: automake: command not found
```

By the way, the INSTALL file still refers to using `./configure` to compile and install the software

**Comment by simsong** [comment]
You need to install autotools.

**Comment by jjarava** [comment]
Hi, @simsong, and how would I go about doing that?

**Comment by simsong** [comment]
There are many ways of doing so. See: http://bit.ly/1diV4Aw

**Comment by jjarava** [comment]
Thanks for the pointer, I've followed the instructions on http://jsdelfino.blogspot.co.uk/2012/08/autoconf-and-automake-on-mac-os-x.html (but they seem to be basically the same) and hashdeep has apparently compiled fine (there were quite a few `warnings` in the output, but I've ended with binaries and manuals etc)....

Is there any "test suite" I could run to validate that the resulting binaries are fine?

Thanks!

**Comment by jessek** [comment]
There are some files in the /tests directory which you can use to test the program against previous versions, but that's probably not what you want. 

Instead you should try downloading known files and verify the hashes posted with them match the hashes you compute. For example, all of the old tar balls for md5deep have the SHA256 hash posted at http://md5deep.sourceforge.net/. Look under 'Older versions'.

**Comment by jjarava** [comment]
Hi! 

Thanks for the suggestion. 

I was under the impression that there was a `make` option to run a test suite. But I must've confused myself with some other project - I've been having a look at quite a few "compile it yourself" projects in the last few days. 

Regards

**Comment by jjarava** [comment]
Closing the issue as I got the info I needed and works (should've done cleanup a long time ago)
