### ISSUE TITLE
md5deep problem with special files

### ISSUE THREAD

**Issue by Autiwa** [jessek/hashdeep#338]
Hello, 

For a few days I've been tracking down a very weird issue. md5deep (v4.2) seems to be in waiting mode indefinitely. 

https://sourceforge.net/p/md5deep/discussion/227841/thread/cfb4ffd7/?limit=25#9626
In the following topic, you can find a bunch of informations about the test I did. And I can do some more if you request. In particular, I linked the strace of the program

By doing a run with the "-j0" option, I think I narrowed down to the problematic folder. And maybe the problematic file. I think the problem comes from this file, because it is special, maybe the sticky bit, I don't know. 

ls -lh of this file gives:
prw------- 1 autiwa autiwa    0 juil.  4 07:19 control

In practice, md5deep wait forever, doesn't return an error, doesn't skip the file. 

If there are some informations missing, feel free to ask.

**Comment by simsong** [comment]
That is a named pipe. The program is waiting for input from the other side of the pipe.

**Comment by jessek** [comment]
Thank you @Autiwa for providing the extra details on the named pipe. @simsong is correct; this is a feature of your filesystem, not a problem with md5deep.

On the other hand, you can have md5deep skip named pipes using expert mode. For example, to limit processing to regular files only:

$ md5deep -o f [FILES]

**Comment by simsong** [comment]
Perhaps the default should be to skip named pipes and only include them in expert mode...

**Comment by Autiwa** [comment]
Thank you for your answers, both of you. I didn't even knew named pipes existed beforehand. 

Simsong, the command you provide seems to work perfectly !. For me, this issue can be closed (I can't close it myself apparently).

**Comment by jessek** [comment]
You're welcome! Glad it helped.
