### ISSUE TITLE
Hash for Integrity Check of v4.4 ZIP Pack of MS-Win Binaries & Stuff?

### ISSUE THREAD

**Issue by Doryforos** [jessek/hashdeep#355]
Forgive me if I am missing something here, but, since a hash used to be published for the zip pack containing the compiled MS-Win executables and docs, in order to verify its integrity, I have looked around to find such a hash for the latest pack and no matter how hard I looked, I couldn't find any.

I had to resort to the next best thing: as I am most of the times using wget to download, I took the ETag from the server messages, that luckily -- as this is not always the case -- is the MD5 sum of this latest zip pack; it verifies OK, but, to me, this is just a rather ugly workaround.

Has any hash for the v4.4 MS-Win zip pack ever been published (and if yes, kindly somebody point me to it, otherwise, Jesse, kindly publish it).

It might have been deemed unnecessary, as the download comes through https, but, then, again, it has always been kind of reassuring to me to have a verification hash for the pack.

Here is the last portion of the MS-WinXP cmd stdout of my wget command (that is on top of the output), for reference:

```
wget --no-check-certificate -SN https://github.com/jessek/hashdeep/releases/download/v4.4/md5deep-4.4.zip -O md5deep-4.4.zip
...
  HTTP/1.1 200 OK
  x-amz-id-2: EI5XsoI4EandON8R9o+hkQgC95z8u2MhZ7Z9hsyp91J/Ij8zg37aqYq19CVJNgMynYZlh8UtxOg=
  x-amz-request-id: A5DE572C95971415
  Date: Fri, 08 Jul 2016 00:18:44 GMT
  Cache-Control: max-age=31557600
  x-amz-meta-surrogate-control: max-age=31557600
  x-amz-meta-surrogate-key: repository-4636548 user-1842175
  Content-Disposition: attachment; filename=md5deep-4.4.zip
  Last-Modified: Wed, 29 Jan 2014 20:34:49 GMT
  ETag: "047ff5311d821f667150f37695bd01b3"
  Accept-Ranges: bytes
  Content-Type: application/octet-stream
  Content-Length: 3792436
  Connection: keep-alive
  Server: AmazonS3
Length: 3792436 (3.6M) [application/octet-stream]
Saving to: `md5deep-4.4.zip'

100%[=================== ... ====================>] 3,792,436    179K/s   in 36s

2016-07-08 03:19:09 (103 KB/s) - `md5deep-4.4.zip' saved [3792436/3792436]
```

In any case, many thanks for making publically available this wonderful suite of integrity checking applications!

**Comment by jessek** [comment]
I'm not sure how to publish these on the release page, but here are the hashes for the Windows ZIP:

MD5 047ff5311d821f667150f37695bd01b3
SHA256 d5e85933e74e5ba6a73f67346bc2e765075d26949c831a428166c92772f67dbc

**Comment by Doryforos** [comment]
Thank you very much!

Why not publish the hash(-es) in the README.md file, though?

All the best!

**Comment by jessek** [comment]
I've added these hashes to the README.md. Thanks for the suggestion!
