### ISSUE TITLE
[EXPIRED] Russian filenames are garbled

### ISSUE THREAD

**Issue by sergeevabc** [jessek/hashdeep#363]
7x64, md5deep 4.4

1. Create empty ```привет.txt```
2. Execute ```md5deep привет.txt```
3. Output is garbled as follows
![1]

Current workaround to get valid output with Russian characters is to execute ```chcp 65001``` beforehand. However this extra step is not comfortable. @jessek, could you do something about that, please?

[1]: https://vgy.me/6PplQc.png

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by ethus3h** [comment]
@jessek hasn't been on GitHub much lately, it doesn't seem. If this is an urgent problem, you could fix [the other bug in the situation](https://stevwebservice.wordpress.com/2008/03/19/windows-is-a-bug/)... ;)

**Comment by simsong** [comment]
Hello.
