### ISSUE TITLE
Turn off following symlinks in recursive mode

### ISSUE THREAD

**Issue by steveb-cirina** [jessek/hashdeep#371]
Hi

In order to use md5deep in recursive mode but have it skip just symlinks, I ran it in the following way in "expert" mode (leaving out `l` from the `-o` option):

`md5deep -o fbcpsd ...`

Is there a short hand way to do this (i.e. just turn off symlinks) ?

Thanks.

**Comment by jessek** [comment]
Sorry, no. The expert mode code was written with only support to add modes, not exclude them.

**Comment by steveb-cirina** [comment]
Ok, thanks.
