### ISSUE TITLE
md5deep -jn flag

### ISSUE THREAD

**Issue by stanley3384** [jessek/hashdeep#378]
Please take a look at my terminal experiments.  After a bit of
experimenting I changed the flags "rwXj4" to  "-j4 -r -w -X". Putting the
flags in a different order also failed "-r -w -X -j4".  I'm running md5deep
version 4.2.  I'm only reporting this to you as I'm not sure if it's normal
or a wee bit un-Linux/UNIX. Regards Ian.

 md5deep -trj4  My_Education > hash

 md5deep  -j4 -r -w -X   hash My_Education
3d74b19e05b8894061ad0e99218f1f74
/home/stan/My_Education/gcc/SDL/SDL_DisplayBitmap/image.bmp does NOT match
//    As expected, md5 sum tampered

md5deep  -rwXj4   hash My_Education
md5deep: j4: No such file or directory
md5deep: Unable to load any matching files.
Try `md5deep -h` for more information.
//    Failed, not expected

**Comment by jessek** [comment]
It took me a minute, but I figured out what's going on here. The -X flag requires a filename immediately following the argument. In the order you have them:

  $ md5deep -rwXj4 

the system is attempting to use j4 as the filename for the -X argument; hence the error you see "j4: No such file or directory." Any of these variations should work:

$ md5deep -j4 -wrX hash My_Education
$ md5deep -wrXhash -j4 My_Education
